services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.template
    mem_limit: 0.5g
    ports:
      - 0:5432
    environment:
      POSTGRES_PASSWORD: postgres
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: replication
      REPLICATION_SLOT: slot_standby
    volumes:
      - ./init-script-example.sh:/entrypoint.d/init-script-example.sh
      - ./init-script-example.sql:/entrypoint.d/init-script-example.sql
    # entrypoint: ["sleep", "infinity"]
  slave:
    build:
      context: .
      dockerfile: Dockerfile.template
    ports:
      - 0:5432
    mem_limit: 0.5g
    environment:
      POSTGRES_HOST: master
      POSTGRES_PORT: 5432
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: replication
      REPLICATION_SLOT: slot_standby
    # entrypoint: ["sleep", "infinity"]
  pgbouncer:
    build:
      context: .
      dockerfile: Dockerfile.template
      target: pgbouncer
    ports:
      - 0:6432
    mem_limit: 0.5g
    environment:
      PGBOUNCER_ADMIN_USER: admin
      PGBOUNCER_ADMIN_PASSWORD: admin
      PGBOUNCER_DATABASES: master=postgres:5432,slave=postgres:5432
    # entrypoint: ["sleep", "infinity"]
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.template
      target: haproxy
    ports:
      - 0:5432
    mem_limit: 0.5g
    environment:
      HAPROXY_BACKENDS: master=master:5432,slave=slave:5432
    entrypoint: ["sleep", "infinity"]
