services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.template
    mem_limit: 0.5g
    ports:
      - 0:5432
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: replication
      REPLICATION_SLOT: slot_standby
      SUPERUSER_USER: postgres
      SUPERUSER_PASSWORD: postgres
    volumes:
      - ./init-script-example.sh:/entrypoint.d/init-script-example.sh
      - ./init-script-example.sql:/entrypoint.d/init-script-example.sql
    # entrypoint: ["sleep", "infinity"]
  slave:
    build:
      context: .
      dockerfile: Dockerfile.template
    ports:
      - 0:5432
    mem_limit: 0.5g
    environment:
      POSTGRES_HOST: master
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: replication
      REPLICATION_SLOT: slot_standby
    # entrypoint: ["sleep", "infinity"]
