version: "3.8"
services:
  pgsql-writer:
    container_name: pgsql-writer
    image: devoptimus/postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: "postgres"
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-q"]
      interval: 15s
    ports:
      - "5432:5432"
  pgsql-reader:
    container_name: pgsql-reader
    image: devoptimus/postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: "postgres"
    env_file: .env
    environment:
      - REPLICATION_MODE=slave
    depends_on:
      pgsql-writer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-q"]
      interval: 15s
    ports:
      - "5433:5432"
